services:
  - type: web
    name: kodflix-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 14506
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: defaultdb
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://kodflix-frontend.onrender.com
